### ISSUE TITLE
Unable to create eslintrc for IDE linter

### ISSUE THREAD

**Issue by cyberwombat** [mozilla-neutrino/neutrino-dev#265]
I am unclear on the process on how to create a proper eslintrc for my IDE. I have read the docs [here](https://neutrino.js.org/middleware/neutrino-middleware-eslint/#eslintrc-config) and created  an .`eslintrc.js` file with this:
````
const { Neutrino } = require('neutrino');
const api = Neutrino();

module.exports = api.call('eslintrc');
````
Running my linter I get:
````
Cannot read config file: /node-starter-master/.eslintrc.js
Error: Cannot find module '.neutrinorc.js'
````

This is the part I am unclear on. Docs mention creating a Neutrino API but I am not sure what goes in there. I have added:
````
module.exports = {
  use: [
     "neutrino-preset-airbnb-base",
      "neutrino-preset-node",
      "neutrino-middleware-eslint"
  ]
}
````
But that did not help at all.

Can someone clarify this process?  Thank you.

**Comment by eliperelman** [comment]
Hello! The Neutrino API call method automatically looks for a .neutrinorc.js file if you don't pass any middleware. The airbnb preset already includes the asking middleware, so try putting this in a .neutrinorc.js file in the root of your project:

```js
module.exports = {
  use: [
    'neutrino-preset-airbnb-base',
    'neutrino-preset-node',
  ]
};
```

It should work from there. If you don't want to create a .neutrinorc.js file, you can also pass those two presets into the call method:

```js
const { Neutrino } = require('neutrino');
const api = Neutrino();

module.exports = api.call('eslintrc', [
  'neutrino-preset-airbnb-base',
  'neutrino-preset-node',
]);
```

Give one of those a shot.

**Comment by cyberwombat** [comment]
Ok the second semi-works. The first one is what I started with and fails with the `Error: Cannot find module '.neutrinorc.js'` error.

The second method is outputting eslint config but is adding a couple of extra fields" `cwd` and `useEslintrc` which afaik are not valid .eslintrc fields but command line params. 

````
{ cwd: '/Users/Yashua/Desktop/node-starter-master/src',
  useEslintrc: true,
  root: true,
  plugins: [ 'babel' ],
  extends: [ 'airbnb-base' ],
  env: { es6: true },
  parser: 'babel-eslint',
  parserOptions: 
   { ecmaVersion: 2017,
     sourceType: 'module',
     ecmaFeatures: 
      { objectLiteralDuplicateProperties: false,
        generators: true,
        impliedStrict: true } },
  settings: {},
  globals: { process: true },
  rules: 
   { 'new-cap': 'off',
     'object-curly-spacing': 'off',
     'babel/new-cap': [ 'error', [Object] ],
     'babel/object-curly-spacing': [ 'error', 'always' ] } }
````

Linter throws this error:
````
ESLint configuration is invalid:
- Unexpected top-level property "cwd".
- Unexpected top-level property "useEslintrc".
````

**Comment by eliperelman** [comment]
Can y oiu share your package.json? Did you install eslint manually?

**Comment by cyberwombat** [comment]
Here's my `package.json`:
````
{
  "version": "1.0.0",
  "private": true,
  "description": "Get started with Node!",
  "main": "index.js",
  "engines": {
    "node": ">=6.9"
  },
  "scripts": {
    "start": "neutrino start",
    "build": "neutrino build"
  },
  "author": "Hassan Ali <helfi92@gmail.com>",
  "license": "MIT",
  "devDependencies": {
    "eslint-config-airbnb-base": "^11.2.0",
    "neutrino": "^6.0.2",
    "neutrino-preset-airbnb-base": "^6.0.2",
    "neutrino-preset-node": "^6.0.2",
    "eslint": "^3.19.0",
    "eslint-plugin-import": "^2.2.0"
  },
  "dependencies": {
    
  }
}

````
After your eslint comment I looked into it and i am/was running ESllint v4. It seems the config my have changed hence the errors. I then installed eslint v3 locally which addresses the cwd/useeslintrc errors in favor for another which may be unrelated:
````
{ Error: ENOENT: no such file or directory, scandir 'node_modules'
    at Object.fs.readdirSync (fs.js:870:18)
    at readDir (/node-starter-master/node_modules/webpack-node-externals/index.js:12:19)
    at nodeExternals (/node-starter-master/node_modules/webpack-node-externals/index.js:95:65)
    at module.exports (/node-starter-master/node_modules/neutrino-preset-node/index.js:73:17)
```

**Comment by eliperelman** [comment]
Can you uninstall `eslint-config-airbnb-base`, `eslint`, and `eslint-plugin-import` and try again?

**Comment by eliperelman** [comment]
And correct, the eslint stuff doesn't support ESLint v4 yet: #244.

One thing to keep in mind with Neutrino is we try to wrap up the transitive dependencies for specific middleware for you. That means if you use `neutrino-middleware-airbnb-base`, you don't have to install the eslint middleware, eslint, the eslint configs, or anything. Just as long as you have Neutrino and a preset, you should be good to go.

**Comment by cyberwombat** [comment]
I understand but here's what happens. If I just start with this:
````
"devDependencies": {
    "neutrino": "^6.0.2",
    "neutrino-preset-airbnb-base": "^6.0.2",
    "neutrino-preset-node": "^6.0.2"   
  },
````
I remove all node_modules and run yarn. I then get:
````
warning Unmet peer dependency "eslint@^3.19.0".
warning Unmet peer dependency "eslint-plugin-import@^2.2.0".
````
Let's say I ignore these. My linter fails because I have no eslint executable. So I globally then install v3. The linter now says:
````
Cannot find module 'eslint-config-airbnb-base'
Referenced from: //node-starter-master/.eslintrc.js
````
Because the outputted `.eslintrc` contains `extends: [ 'airbnb-base' ]`

And so on.. Which is why I ended up having to install each single package.

**Comment by eliperelman** [comment]
I just tried to replicate with a little repo:

https://github.com/eliperelman/replicate-eslint

I've added 2 scripts:

`yarn lint` - runs `neutrino lint`
`yarn eslint` - runs eslint

Can you try that out? I didn't receive any peerDependency warnings, although that can happen on a first install when nothing has been added yet.

**Comment by cyberwombat** [comment]
Ok. I got the same peer dependencies warning about `eslint` and `eslint-plugin-import`. Ignoring...
Linting a file (I use SublimeLinter) I get:
````
 problem 
SublimeLinter: eslint: index.js ['/usr/local/bin/eslint', '--format', 'compact', '--stdin', '--stdin-filename', '@'] 
SublimeLinter: eslint output:
Cannot read config file: /replicate-eslint-master/.eslintrc.js
Error: Cannot find module '.neutrinorc.js'
Error: Cannot read config file: /Ureplicate-eslint-master/.eslintrc.js
Error: Cannot find module '.neutrinorc.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.require (/replicate-eslint-master/node_modules/neutrino/src/api.js:86:14)
 ````
The eslint version at `/usr/local/bin/eslint' is `v3.19.0`. I have tried this with Node 6.7 and 7.2.

I get no errors when running `yarn lint` - just my IDE. While I specified I needed an `.eslintrc` for my IDE I realize that it may have been lost in the thread that this is where the errors are coming from.
`

This is the same error I got initially.

**Comment by cyberwombat** [comment]
If I install `eslint` v3.x locally for my IDE to use I get the same `Error: Cannot find module '.neutrinorc.js'` error.

**Comment by cyberwombat** [comment]
Ok. So the `api.js` file in the neutrino packages fails on finding the rc file. It doesn't try the root of the project but instead checks `src/` and `src/node_modules/` instead.

**Comment by eliperelman** [comment]
Ah interesting, I missed that. I'll have to do some more digging.

**Comment by constgen** [comment]
Successfully installed without an error on WIndows 8.1 with NPM. ESLint works in VSCode and highlights errors. Autofix also works.

**Comment by constgen** [comment]
But have an issue when try to a new project myself. The extension throws an error
```
Cannot read config file: c:\Users\Genchevsky\Desktop\web-test\.eslintrc.js Error: api.commands[commandName] is not a function
```
Here is my setup 
https://mega.nz/#!zZFVkJjK!8Xoa5qLbCO9SFe9yZFEqVrlN2zY15URVRGf1SlEtD4I

**Comment by constgen** [comment]
By the way `npm start` doesn't work also
```
? Building project failed
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.

 - configuration misses the property 'entry'.
   object { <key>: non-empty string | [non-empty string] } | non-empty string | [non-empty string] | function
   The entry point(s) of the compilation.
    at ChainAction.validator.chain.errors [as mapper] (C:\Users\Genchevsky\Desktop\web-test\node_modules\neutrino\src\webpack.js:49:20)
    at ChainAction.resolved (C:\Users\Genchevsky\Desktop\web-test\node_modules\fluture\index.js:655:83)
    at resolved (C:\Users\Genchevsky\Desktop\web-test\node_modules\fluture\index.js:162:19)
    at Future$1._fork (C:\Users\Genchevsky\Desktop\web-test\node_modules\fluture\index.js:550:3)
    at drain (C:\Users\Genchevsky\Desktop\web-test\node_modules\fluture\index.js:215:25)
    at settle (C:\Users\Genchevsky\Desktop\web-test\node_modules\fluture\index.js:148:17)
    at resolved (C:\Users\Genchevsky\Desktop\web-test\node_modules\fluture\index.js:162:5)
    at Timeout.escaped [as _onTimeout] (C:\Users\Genchevsky\Desktop\web-test\node_modules\fluture\index.js:42:34)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
```

**Comment by eliperelman** [comment]
@constgen your `.neutrinorc.js` has `module.export`; it should be `module.exports`.

**Comment by constgen** [comment]
Really, this small typo broke everything. Now building and ESlint integration works on 100%. Thanks.

User friendly error messages would be useful for such cases. But I understand that we don't have any handlers for them. May be we can write some separate checker of the project structure that will just validate the project structure. This validator will be launched on `prerun`.
It will decrease the amount of issues in GitHub in the future.

**Comment by barraponto** [comment]
`module.export` typo is dealt with by node machinery. it could definitely have a better error message, but it's totally out of scope for neutrino :(

**Comment by barraponto** [comment]
@cyberwombat did you fix it? maybe your editor needs to be configured to run `eslint` from the right folder. I had that issue with vim's syntastic, and I had to use (even write) plugins to fix that :/

**Comment by edmorley** [comment]
Perhaps one way to avoid this would be to have a `neutrino init` command that created a skeleton config, thereby avoiding having to type/copy paste and make these kind of typos? It could use a combination of prompts and auto-detection to determine what the project layout is, what middleware to enable etc.

**Comment by barraponto** [comment]
not sure about a `neutrino init` command, but maybe a script that generates `.eslintrc` and other local configuration files (such as `stylelint.config.js`)

**Comment by constgen** [comment]
This `neutrino init`, does it mean that the user will also need to install it globally?

**Comment by metamas** [comment]
I was having issues with this as well, running `neutrino 6.0.4`. Below is what got everything working smoothly with my Atom setup. As you'll see, some repetitiveness was necessary.

```js
// .neutrinorc.js

module.exports = {
  use: [
    [
      'neutrino-preset-airbnb-base',
      {
        eslint: {
          baseConfig: {
            extends: ['plugin:react/recommended']
          }
        }
      }
    ],
    'neutrino-preset-react'
  ]
};
```

```js
// .eslintrc.js

const { Neutrino } = require('neutrino');
const api = Neutrino();

module.exports = api.call('eslintrc', [
  ['neutrino-preset-airbnb-base',
    {
      eslint: {
        baseConfig: {
          extends: ['plugin:react/recommended']
        }
      }
    }
  ],
  'neutrino-preset-react'
]);
```
 If anyone knows of a way to improve this current setup, I'm all 👂s.

**Comment by jackysee** [comment]
Hi, I found error running .eslintrc.js

```
C:\workspace\app>node .eslintrc.js
C:\workspace\app\node_modules\ramda\src\internal\_reduce.js:59
    throw new TypeError('reduce: list must be array or iterable');
    ^

TypeError: reduce: list must be array or iterable
    at _reduce (C:\workspace\app\node_modules\ramda\src\internal\_reduce.js:59:11)
    at C:\workspace\app\node_modules\ramda\src\internal\_curry3.js:26:46
    at f1 (C:\workspace\app\node_modules\ramda\src\internal\_curry1.js:17:17)
    at evolve (C:\workspace\app\node_modules\ramda\src\evolve.js:37:57)
    at C:\workspace\app\node_modules\ramda\src\internal\_curry2.js:20:46
    at f1 (C:\workspace\app\node_modules\ramda\src\internal\_curry1.js:17:17)
    at C:\workspace\app\node_modules\ramda\src\internal\_pipe.js:3:14
    at C:\workspace\app\node_modules\ramda\src\internal\_arity.js:5:45
    at Object.neutrino.register [as eslintrc] (C:\workspace\app\node_modules\neutrino-middleware-eslint\index.js:77:39)
    at Object.call (C:\workspace\app\node_modules\neutrino\src\api.js:167:39)
    at Object.<anonymous> (C:\workspace\app\.eslintrc.js:17:22)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```

my .eslintrc.js
```js
const { Neutrino } = require('neutrino');
const api = Neutrino();
module.exports = api.call('eslintrc', [
    'neutrino-preset-web',
    './override-web.js',
    'neutrino-preset-vue'
]);
```

In `override-web.js`, it uses the middleware
```js
    const eslint = require('neutrino-middleware-eslint');
    neutrino.use(eslint, {
        eslint: {
            envs: ['browser', 'es6', 'commonjs'],
            baseConfig: {
                extends: ['eslint:recommended', 'prettier']
            },
            rules: {
                indent: ['error', 4],
                'linebreak-style': ['off', 'windows'],
                quotes: ['error', 'single'],
                semi: ['error', 'always']
            }
        }
    });
```
I found that the problem comes from `neutrino-preset-vue`  (https://github.com/barraponto/neutrino-preset-vue/blob/master/src/index.js). Here is the code that touch the lint rule:
```js
  if (lintRule) {
    // ensure conditions is an array of original values plus our own regex
    const conditions = arrify(lintRule.get('test')).concat([LOADER_EXTENSIONS]);
    config.module
      .rule('lint')
      .test(conditions)
      .use('eslint')
      .tap(options => merge(options, {
        plugins: ['vue'],
        env: { node: true },
        rules: {
          'vue/jsx-uses-vars': 2
        }
      }));
  }
```

I'm not sure if this code is correct, or something should be catered in the `neutrino-middlware-eslint`?

**Comment by jackysee** [comment]
for the `neutrino-preset-vue` issue, it could be fix by making an override:
```js
module.exports = neutrino => {
    neutrino.config.module.rule('lint').use('eslint').tap(options => {
        delete options.env;
        options.envs.push('node');
        return options;
    });
};
```
So the problem is that the eslint config uses `envs` but the preset uses `env`, still not sure which one is correct though.

**Comment by barraponto** [comment]
It used to be `env`, now it's `envs`. I fixed it in my preset, but shouldn't we add it to https://neutrino.js.org/upgrading-neutrino.html ?

**Comment by barraponto** [comment]
@metamas you can avoid duplication by requiring `.neutrinorc.js`

```javascript
// .eslintrc.js

const { Neutrino } = require('neutrino');
const config = require('./.neutrinorc');
const api = Neutrino();

module.exports = api.call('eslintrc', config.use);
```

However, looking at AtomLinter/linter-eslint#964 it seems like just creating a `.eslintignore` file in the same folder as the `.eslintrcjs` should make `linter-eslint` pick up the project directory.

**Comment by eliperelman** [comment]
> It used to be env, now it's envs. I fixed it in my preset, but shouldn't we add it to https://neutrino.js.org/upgrading-neutrino.html ?

The layout of a standard `.eslintrc.js` is different than the options that are passed to ESLint's CLIEngine, which is what is used by our commands and the eslint-loader. We have to perform a transformation of the config from one format to the other in order to use eslint programmatically. It has always been this way unfortunately.

**Comment by eliperelman** [comment]
I believe the original issue here has been worked around to the best of our ability. If an issue still exists, please open a new one. Thanks!
